In [1]:
import requests
import pandas as pd
import time

all_records = []

for page in range(1, 6):

    url = (f"https://api.coingecko.com/api/v3/coins/markets"
           
           f"?vs_currency=inr&per_page=250&order=market_cap_desc"
           f"&page={page}&sparkline=False")

    response = requests.get(url)
    all_data = response.json()

    if response.status_code != 200:
       print(f"Error on page {page}: {response.status_code}")
       time.sleep(20)
       continue

    for i in all_data:
        all_records.append(dict(
            id=i["id"],
            symbol=i["symbol"],
            name=i["name"],
            current_price=i["current_price"],
            market_cap=i["market_cap"],
            market_rank=i["market_cap_rank"],
            total_volume=i["total_volume"],
            circulating_supply=i["circulating_supply"],
            total_supply=i["total_supply"],
            ath=i["ath"],
            atl=i["atl"],
            last_updated=i["last_updated"]
        ))


    time.sleep(20)


coins_df = pd.DataFrame(all_records)

coins_df["last_updated"] = pd.to_datetime(coins_df["last_updated"], errors="coerce").dt.date

coins_df

#completed all 5 pages readed

,id,symbol,name,current_price,market_cap,market_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,7.358345e+06,147741098006360,1.0,2.862196e+12,2.007848e+07,2.007851e+07,11187013.00,3993.420000,2026-09-02
1,ethereum,eth,Ethereum,2.296780e+05,27716236439109,2.0,1.277089e+12,1.206797e+08,1.212039e+08,431946.00,28.130000,2026-09-02
2,tether,usdt,Tether,9.483000e+01,17389691472071,3.0,5.098952e+12,1.833795e+11,1.888465e+11,105.52,36.860000,2026-09-02
3,binancecoin,bnb,BNB,6.527100e+04,8691596071249,4.0,7.834813e+10,1.331623e+08,1.331623e+08,121422.00,2.580000,2026-09-02
4,ripple,xrp,XRP,1.278300e+02,8018493824940,5.0,2.170410e+11,6.274450e+10,9.998563e+10,313.99,0.159343,2026-09-02
...,...,...,...,...,...,...,...,...,...,...,...,...
1245,buttcoin-7,buttcoin,Buttcoin,9.245590e-01,924632206,1180.0,9.847455e+07,9.999428e+08,9.999428e+08,4.48,0.307927,2026-09-02
1246,solid-x,solidx,Solid X,4.402000e+01,924456508,1181.0,4.680530e+05,2.100000e+07,2.100000e+07,4520.29,10.540000,2026-09-02
1247,thena,the,Thena,6.710000e+00,920325285,1183.0,3.012463e+08,1.372564e+08,2.886689e+08,340.46,4.360000,2026-09-02
1248,moonriver,movr,Moonriver,7.294000e+01,916761452,1184.0,3.962357e+08,1.256839e+07,1.256839e+07,36341.00,59.760000,2026-09-02
1249,swarm-3,sn124,Swarm,2.438400e+02,915580146,1185.0,3.174972e+07,3.754824e+06,3.754824e+06,351.90,1.210000,2026-09-02

In [2]:
coins_df.isnull().sum()

id                    0
symbol                0
name                  0
current_price         0
market_cap            0
market_rank           6
total_volume          0
circulating_supply    0
total_supply          1
ath                   0
atl                   0
last_updated          0
dtype: int64

In [3]:
import pandas as pd 
import requests
import time

coin_ids = ["bitcoin","ethereum","tether","binancecoin","ripple"]

all_data =[]

for coin_id in coin_ids:
    url = f"https://api.coingecko.com/api/v3/coins/{coin_id}/market_chart?vs_currency=usd&days=365"
    response = requests.get(url)
    
    if response.status_code != 200:
       print(f"Error fetching {coin_id}: {response.status_code}")
       continue
        
    data = response.json()
    
    if 'prices' not in data:
        print(f"No price data for {coin_id}: {data}")
        continue
         
    all_data.extend([{
    "coin_id": coin_id,
    "date": pd.to_datetime(ts, unit='ms').date(),
    "price_usd": price
     } 
     for ts, price in data['prices']])


    time.sleep(10)

top_df = pd.DataFrame(all_data)

top_df



#completed top 5 crypto  historical prices

      coin_id        date      price_usd
0     bitcoin  2025-09-03  111348.104293
1     bitcoin  2025-09-04  111751.647610
2     bitcoin  2025-09-05  110752.041425
3     bitcoin  2025-09-06  110656.308978
4     bitcoin  2025-09-07  110223.833959
...       ...         ...            ...
1825   ripple  2026-08-30       1.396292
1826   ripple  2026-08-31       1.357927
1827   ripple  2026-09-01       1.379280
1828   ripple  2026-09-02       1.351465
1829   ripple  2026-09-02       1.347940

[1830 rows x 3 columns]

In [4]:
import pandas as pd

oil_df = pd.read_csv("https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv")

oil_df["Date"] = pd.to_datetime(oil_df["Date"])

filtered_oil_df = oil_df[
    (oil_df["Date"] >= "2020-01-01")&
    (oil_df["Date"] <= "2026-01-31")
]

filtered_oil_df


#oil_prices from jan2020 to jan2026 completed

            Date  Price
8569  2020-01-02  61.17
8570  2020-01-03  63.00
8571  2020-01-06  63.27
8572  2020-01-07  62.70
8573  2020-01-08  59.65
...          ...    ...
10084 2026-01-26  60.46
10085 2026-01-27  62.04
10086 2026-01-28  62.75
10087 2026-01-29  64.77
10088 2026-01-30  64.50

[1520 rows x 2 columns]

In [5]:
import yfinance as yf
import pandas as pd

tickers = ["^GSPC","^IXIC","^NSEI"]
start_date = "2020-01-01"
end_date = "2026-01-31"

stocks_df = yf.download(tickers,start = start_date,end = end_date, group_by ="ticker")

gspc_df = stocks_df["^GSPC"].reset_index().dropna()
gspc_df["Ticker"] = "^GSPC"
gspc_df.rename(columns={"Date": "date"}, inplace=True)

nsei_df = stocks_df["^NSEI"].reset_index().dropna()
nsei_df["Ticker"] = "^NSEI"
nsei_df.rename(columns={"Date": "date"}, inplace=True)

ixic_df = stocks_df["^IXIC"].reset_index().dropna()
ixic_df["Ticker"] = "^IXIC"
ixic_df.rename(columns={"Date": "date"}, inplace=True)

all_stocks_df = pd.concat([gspc_df, ixic_df, nsei_df], ignore_index=True)

all_stocks_df

[*********************100%***********************]  3 of 3 completed

Price,date,Open,High,Low,Close,Volume,Ticker
0,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09,^GSPC
1,2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3.484700e+09,^GSPC
2,2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3.702460e+09,^GSPC
3,2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3.435910e+09,^GSPC
4,2020-01-08,3238.590088,3267.070068,3236.669922,3253.050049,3.726840e+09,^GSPC
...,...,...,...,...,...,...,...
4557,2026-01-23,25344.599609,25347.949219,25025.300781,25048.650391,3.939000e+05,^NSEI
4558,2026-01-27,25063.349609,25246.650391,24932.550781,25175.400391,6.187000e+05,^NSEI
4559,2026-01-28,25258.849609,25372.099609,25187.650391,25342.750000,5.749000e+05,^NSEI
4560,2026-01-29,25345.000000,25458.150391,25159.800781,25418.900391,5.824000e+05,^NSEI
4561,2026-01-30,25247.550781,25370.699219,25213.650391,25320.650391,5.084000e+05,^NSEI

In [ ]:
#data frames are finished

In [12]:
pip install PyMySQL

Defaulting to user installation because normal site-packages is not writeable
Collecting PyMySQL
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: PyMySQL
Successfully installed PyMySQL-1.2.0
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# mysql conncection ,tables creation and data insertions

In [1]:
import pymysql

conn = pymysql.connect(
    host="localhost",
    port=3306,
    user="root",
    password="goku",
    
)

cpa_cursor = conn.cursor()

print("connection successfully")

connection successfully

In [14]:
cpa_cursor.execute("CREATE DATABASE IF NOT EXISTS cross_platform_analysis")

print("data base ready")

data base ready

In [9]:
cpa_cursor.execute("USE cross_platform_analysis")

print("database connected")

database connected

In [27]:
cpa_cursor.execute("DROP TABLE IF EXISTS crypto_currencies")
conn.commit()

print("table deleted")

table deleted

In [28]:
cpa_cursor.execute("""CREATE TABLE IF NOT EXISTS crypto_currencies(
id VARCHAR(255) PRIMARY KEY,
symbol VARCHAR(20),
name VARCHAR(100),
current_price DECIMAL(18,6),
market_cap BIGINT,
market_rank INT,
total_volume BIGINT,
circulating_supply DECIMAL(40,6),
total_supply DECIMAL(40,6),
ath DECIMAL(18,6),
atl DECIMAL(18,6),
last_updated DATE
)""")

conn.commit()


print("table created")

table created

In [45]:
cpa_cursor.execute("TRUNCATE TABLE crypto_currencies")

conn.commit()

print("table cleared")

table cleared

In [46]:
import numpy as np

coins_df = coins_df.replace({np.nan:None})

insert_query = """INSERT INTO crypto_currencies(
id,symbol,name,current_price,market_cap,
market_rank,total_volume,
circulating_supply,
total_supply,ath,atl,last_updated
)
VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"""

for _, row in coins_df.iterrows():
    cpa_cursor.execute(insert_query,(
        row["id"],
        row["symbol"],
        row["name"],
        row["current_price"],
        row["market_cap"],
        row["market_rank"],
        row["total_volume"],
        row["circulating_supply"],
        row["total_supply"],
        row["ath"],
        row["atl"],
        row["last_updated"]
    ))
conn.commit()

print("Inserted Successfully")

Inserted Successfully

In [47]:
print(coins_df["id"].duplicated().sum())

0

In [48]:
dup_ids = coins_df[coins_df["id"].duplicated()]["id"]
print(dup_ids)

Series([], Name: id, dtype: str)

In [49]:
cpa_cursor.execute("SELECT COUNT(*) FROM crypto_currencies")
print(cpa_cursor.fetchone())

(1249,)

In [50]:
coins_df = coins_df.drop_duplicates(subset=["id"])

print("duplicates removed")

duplicates removed

In [44]:
cpa_cursor.execute("DESCRIBE crypto_currencies")
print(cpa_cursor.fetchall())

(('id', 'varchar(255)', 'NO', 'PRI', None, ''), ('symbol', 'varchar(20)', 'YES', '', None, ''), ('name', 'varchar(100)', 'YES', '', None, ''), ('current_price', 'decimal(18,6)', 'YES', '', None, ''), ('market_cap', 'bigint', 'YES', '', None, ''), ('market_rank', 'int', 'YES', '', None, ''), ('total_volume', 'bigint', 'YES', '', None, ''), ('circulating_supply', 'decimal(40,6)', 'YES', '', None, ''), ('total_supply', 'decimal(40,6)', 'YES', '', None, ''), ('ath', 'decimal(18,6)', 'YES', '', None, ''), ('atl', 'decimal(18,6)', 'YES', '', None, ''), ('last_updated', 'date', 'YES', '', None, ''))

In [ ]:
#coins_df inserted successfully

In [51]:
cpa_cursor.execute("""CREATE TABLE IF NOT EXISTS crypto_prices(
coin_id VARCHAR(50),
date DATE,
price_usd DECIMAL(18,6)
) """)

print("table created")

table created

In [52]:
cpa_cursor.execute("TRUNCATE TABLE crypto_prices")
conn.commit()

print("Old data cleared ✅")

Old data cleared ✅

In [6]:
cpa_cursor.execute("DROP TABLE IF EXISTS crypto_prices")
conn.commit()

print("table deleted")

table deleted

In [53]:
import numpy as np
top_df = top_df.replace({np.nan:None})

insert_query2 = """INSERT INTO crypto_prices(
coin_id,date,price_usd
)VALUES(%s,%s,%s)"""

for _, row in top_df.iterrows():
    cpa_cursor.execute(insert_query2,(
        row["coin_id"],
        row["date"],
        row["price_usd"]
    ))

conn.commit()

print("top_df data inserted in crypto_prices")

top_df data inserted in crypto_prices

In [54]:
cpa_cursor.execute("""CREATE TABLE IF NOT EXISTS oil_prices(
date DATE PRIMARY KEY,
price_usd DECIMAL(18,6)
)""")

print("table created")

table created

In [37]:
cpa_cursor.execute("DROP TABLE IF EXISTS oil_prices")

print("table deleted")

table deleted

In [55]:
cpa_cursor.execute("TRUNCATE TABLE oil_prices")
conn.commit()

print("Old data cleared ✅")

Old data cleared ✅

In [56]:
import numpy as np
filtered_oil_df = filtered_oil_df.replace({np.nan:None})

insert_query3 = """INSERT INTO oil_prices(date,
price_usd)VALUES(%s,%s)"""

for _, row in filtered_oil_df.iterrows():
    cpa_cursor.execute(insert_query3,(
        row["Date"],
        row["Price"]
    ))

conn.commit()

print("filter_oil_df data inserted successfully")

filter_oil_df data inserted successfully

In [57]:
cpa_cursor.execute("""CREATE TABLE IF NOT EXISTS stock_prices(
date DATE,
open DECIMAL(18,6),
high DECIMAL(18,6),
low DECIMAL(18,6),
close DECIMAL(18,6),
volume BIGINT,
ticker VARCHAR(25),
PRIMARY KEY (date, ticker)

)""")

print("table created")

table created

In [58]:
cpa_cursor.execute("TRUNCATE TABLE stock_prices")
conn.commit()

print("Old data cleared ✅")

Old data cleared ✅

In [59]:
import numpy as np

gspc_df = gspc_df.replace({np.nan:None})
nsei_df = nsei_df.replace({np.nan:None})
ixic_df = ixic_df.replace({np.nan:None})

insert_query4 = """INSERT INTO stock_prices(
date,open,
high,low,
close,
volume,
ticker
)VALUES(%s,%s,%s,%s,%s,%s,%s)"""
def insert_df(stocks_df):
   for _, row in stocks_df.iterrows():
       cpa_cursor.execute(insert_query4,(
       row["date"],
       row["Open"],
       row["High"],
       row["Low"],
       row["Close"],
       row["Volume"],
       row["Ticker"],
    
      ))

insert_df(gspc_df)
insert_df(nsei_df)
insert_df(ixic_df)



conn.commit()

print("stocks_df data inserted in stock_prices")

stocks_df data inserted in stock_prices

In [ ]:
# all tables are created and datas inserted successfully

In [ ]:
#sql queries start here

In [ ]:
#cryptocurency queries

In [10]:
import pandas as pd 

top3_crypto = """SELECT id,symbol,name,current_price,
                 total_volume,circulating_supply,
                 total_supply,
                 ath,atl,last_updated
                 FROM crypto_currencies ORDER BY market_cap DESC LIMIT 3;"""

cpa_cursor.execute(top3_crypto)

top3_cryptocurrencies = cpa_cursor.fetchall()

df_top3 = pd.DataFrame(top3_cryptocurrencies,columns = [col[0] for col in cpa_cursor.description])

df_top3

#Find the top 3 cryptocurrencies by market cap completed

,id,symbol,name,current_price,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,7387027.000000,2680510642845,20078215.000000,20078290.000000,11187013.000000,3993.420000,2026-09-01
1,ethereum,eth,Ethereum,232098.000000,1059661238034,120681092.862761,120681092.862761,431946.000000,28.130000,2026-09-01
2,tether,usdt,Tether,94.870000,4686789928792,183378837337.804200,188845783126.696200,105.520000,36.860000,2026-09-01

In [11]:
import pandas as pd

circulatingsupply_exceeds = """SELECT id,symbol,name,current_price,
                                         (circulating_supply/total_supply) * 100 AS supply_percent
                               FROM crypto_currencies
                               WHERE total_supply IS NOT NULL
                                  AND circulating_supply / total_supply > 0.9
                               ORDER BY supply_percent DESC ;"""

cpa_cursor.execute(circulatingsupply_exceeds)

circulatingsupply_exceeds = cpa_cursor.fetchall()

df_exceeds = pd.DataFrame(circulatingsupply_exceeds,columns = [ col[0] for col in cpa_cursor.description])

df_exceeds

#circulating supply exceeds 90% of total supply. completed successfully

,id,symbol,name,current_price,supply_percent
0,balsa-mm-fund,bmmf,Balsa MM Fund,7.940000,19714246.9707158604
1,bermuda-shorts,short,Bermuda Shorts,0.002028,100000.0127500016
2,ubs_umint_eth,umint,UBS USD Money Market Investment Fund Token,10077.760000,208.8836421063
3,brla-digital-brla,brla,BRLA Digital BRLA,18.350000,107.5401191670
4,schuman-europ,europ,EURØP,109.950000,105.8977961386
...,...,...,...,...,...
716,cortex-2,cx,Cortex,1.590000,91.1530422647
717,gamebuild,game,GameBuild,0.077402,91.1248001519
718,moonwell-artemis,well,Moonwell,0.239115,90.5975570400
719,amp-token,amp,Amp,0.042067,90.0330572101
720,ocean-protocol,ocean,Ocean Protocol,13.480000,90.0078012947

In [62]:
import pandas as pd 

all_time_high = """SELECT id,symbol,name,current_price,ath,
                     (current_price/ath) * 100 AS ath_percent
                   FROM crypto_currencies
                   WHERE ath IS NOT NULL
                      AND current_price/ath >= 0.9
                   ORDER BY ath_percent DESC ;"""

cpa_cursor.execute(all_time_high)

all_time_high = cpa_cursor.fetchall()

df_ath = pd.DataFrame(all_time_high,columns = [col[0] for col in cpa_cursor.description])

df_ath

#ALL TIME HIGH COMPLETED

,id,symbol,name,current_price,ath,ath_percent
0,baby-claw,babyclaw,Baby Claw,8.670000,0.043856,19769.2448011675
1,ubs_umint_eth,umint,UBS USD Money Market Investment Fund Token,10077.760000,9764.570000,103.2074121031
2,latam-residential-sstl,pc0000089,Tradable LatAm Residential SSTL,94.900000,92.720000,102.3511647972
3,tradable-singapore-fintech-ssl-2,pc0000023,Tradable Singapore Fintech SSL,94.900000,92.720000,102.3511647972
4,royal-euro,reur,Royal Euro,392.290000,390.950000,100.3427548280
...,...,...,...,...,...,...
174,nvidia-xstock,nvdax,NVIDIA xStock,20888.000000,23017.000000,90.7503149846
175,avant-usd,avusd,Avant USD,94.820000,104.490000,90.7455258876
176,flying-tulip,ft,Flying Tulip,9.610000,10.620000,90.4896421846
177,nvidia-ondo-tokenized-stock,nvdaon,NVIDIA (Ondo Tokenized Stock),20894.000000,23092.000000,90.4815520527
178,usdai,usdai,USDai,94.880000,104.920000,90.4308044224

In [63]:
import pandas as pd

average_rank = """SELECT AVG(market_rank) AS avg_market_cap_rank
                  FROM crypto_currencies
                  WHERE total_volume > 1000000000;"""

cpa_cursor.execute(average_rank)

average_rank = cpa_cursor.fetchall()

df_avgrank = pd.DataFrame(average_rank,columns = [ col[0] for col in cpa_cursor.description])

df_avgrank

#AVG RANK COMPLETED

  avg_market_cap_rank
0            316.3145

In [64]:
import pandas as pd 
  
recently_updated = """SELECT * FROM crypto_currencies
                      AS most_recentlty_updated_coin
                      ORDER BY last_updated DESC
                      LIMIT 1;"""

cpa_cursor.execute(recently_updated)

recently_updated = cpa_cursor.fetchall()

df_recentlyupdated = pd.DataFrame(recently_updated,columns = [col[0] for col in cpa_cursor.description])

df_recentlyupdated

#Get the most recently updated coin. COMPLETED

,id,symbol,name,current_price,market_cap,market_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,0x,zrx,0x Protocol,9.390000,7967503267,305,1840163276,848396562.906836,1000000000.000000,179.790000,6.960000,2026-09-01

In [32]:
#cryptocurrency queries are finished

In [65]:
import pandas as pd 

highest_daily_price = """SELECT MAX(price_usd) AS highest_daily_price FROM
                         crypto_prices
                         WHERE coin_id = "bitcoin"
                         AND date >= CURRENT_DATE - INTERVAL 365 DAY;"""

cpa_cursor.execute(highest_daily_price)

highest_daily_price = cpa_cursor.fetchall()

df_highest_daily_price = pd.DataFrame(highest_daily_price, columns = [col[0] for col in cpa_cursor.description])

df_highest_daily_price

#Find the highest daily price of Bitcoin in the last 365 days. completed

  highest_daily_price
0       124739.810888

In [66]:
import pandas as pd 

avg_daily_price_ethereum = """SELECT AVG(price_usd) AS avg_dailyprice_ethereum 
                              FROM crypto_prices
                              WHERE coin_id = "ethereum"
                              AND date >= CURRENT_DATE - INTERVAL 365 DAY;"""

cpa_cursor.execute(avg_daily_price_ethereum)

avg_daily_price_ethereum = cpa_cursor.fetchall()

df_avg_dailyprice_ethereum = pd.DataFrame(avg_daily_price_ethereum, columns = [col[0] for col in cpa_cursor.description])

df_avg_dailyprice_ethereum

#Calculate the average daily price of Ethereum in the past 1 year. completed

  avg_dailyprice_ethereum
0         2663.5006453197

In [67]:
import pandas as pd 

dailyprice_trend = """SELECT date,price_usd 
                      FROM crypto_prices
                      WHERE coin_id = "bitcoin"
                      AND date BETWEEN "2025-03-01" AND "2025-03-31"
                      ORDER BY date ASC"""

cpa_cursor.execute(dailyprice_trend)

dailyprice_trend = cpa_cursor.fetchall()

bitcoin_dailyprice_trend = pd.DataFrame(dailyprice_trend ,columns = [col[0] for col in cpa_cursor.description])

bitcoin_dailyprice_trend 



#daily price trend of Bitcoin in march 2025.

Empty DataFrame
Columns: [date, price_usd]
Index: []

In [68]:
import pandas as pd

highest_average_price = """SELECT coin_id, AVG(price_usd)
                           AS highest_average_yearly
                           FROM crypto_prices
                           WHERE date >= CURRENT_DATE - INTERVAL 365 DAY
                           GROUP BY coin_id
                           ORDER BY highest_average_yearly
                           DESC LIMIT 1;"""

cpa_cursor.execute(highest_average_price)

highest_average_price = cpa_cursor.fetchall()

highestaverage_coin_price = pd.DataFrame(highest_average_price,columns = [col[0] for col in cpa_cursor.description])

highestaverage_coin_price

#Find the coin with the highest average price over 1 year completed successfully

   coin_id highest_average_yearly
0  bitcoin       82480.4310337268

In [69]:
import pandas as pd

change_in_price = """SELECT ((feb2026.price_usd - feb2025.price_usd)/ feb2026.price_usd)
                     * 100 AS bitcoin_percent_change
                     FROM
                     (SELECT price_usd FROM crypto_prices
                     WHERE coin_id = "bitcoin" AND
                     date BETWEEN "2025-02-01" AND "2025-02-28"
                     ORDER BY date DESC
                     LIMIT 1
                     ) AS feb2025,

                     (SELECT price_usd FROM crypto_prices
                     WHERE coin_id = "bitcoin" AND
                     date BETWEEN "2026-02-01" AND "2026-02-28"
                     ORDER BY date DESC
                     LIMIT 1) AS feb2026;
                  """

cpa_cursor.execute(change_in_price)

change_in_price = cpa_cursor.fetchall()

bitcoin_percent_change = pd.DataFrame(change_in_price,columns = [col[0] for col in cpa_cursor.description])

bitcoin_percent_change

#Get the % change in Bitcoin’s price between feb 2025 to feb 2026 completed

Empty DataFrame
Columns: [bitcoin_percent_change]
Index: []

In [38]:
#crypto_prices query finished

In [70]:
import pandas as pd 

highest_oil_price = """SELECT MAX(price_usd) AS 
                       highest_oil_price_of_5years 
                       FROM oil_prices
                       WHERE date >= CURRENT_DATE - INTERVAL 5 YEAR
                       ORDER BY price_usd DESC
                       LIMIT 1;"""

cpa_cursor.execute(highest_oil_price)

highest_oil_price = cpa_cursor.fetchall()

highest_oil_price_of_5years = pd.DataFrame( highest_oil_price,columns =[col[0] for col in cpa_cursor.description])

highest_oil_price_of_5years 

#Find the highest oil price in the last 5 years completely

  highest_oil_price_of_5years
0                  123.640000

In [71]:
import pandas as pd 

average_oil_price = """SELECT 
                       YEAR(date) AS year,
                       AVG(price_usd) AS average_oil_price_per_year
                       FROM oil_prices
                       GROUP BY YEAR(date)
                       ORDER BY year;"""

cpa_cursor.execute(average_oil_price)

average_oil_price = cpa_cursor.fetchall()

average_oil_price_per_year = pd.DataFrame(average_oil_price, columns = [col[0] for col in cpa_cursor.description])

average_oil_price_per_year

#average oil price per year completed

   year average_oil_price_per_year
0  2020              39.1604365079
1  2021              68.1350996016
2  2022              94.9028685259
3  2023              77.5765322581
4  2024              76.6322400000
5  2025              65.3881048387
6  2026              60.0370000000

In [72]:
import pandas as pd 

covid_oil_prices = """SELECT date,price_usd FROM oil_prices
                      WHERE date BETWEEN "2020-03-01" AND "2020-04-30"
                      ORDER BY date ASC"""

cpa_cursor.execute(covid_oil_prices)

covid_oil_prices = cpa_cursor.fetchall()

covid_crash = pd.DataFrame(covid_oil_prices,columns =[col[0] for col in cpa_cursor.description])

covid_crash

#COVID crash (March–April 2020) completed successfully

          date   price_usd
0   2020-03-02   46.780000
1   2020-03-03   47.270000
2   2020-03-04   46.780000
3   2020-03-05   45.900000
4   2020-03-06   41.140000
5   2020-03-09   31.050000
6   2020-03-10   34.470000
7   2020-03-11   33.130000
8   2020-03-12   31.560000
9   2020-03-13   31.720000
10  2020-03-16   28.960000
11  2020-03-17   26.960000
12  2020-03-18   20.480000
13  2020-03-19   25.090000
14  2020-03-20   19.480000
15  2020-03-23   23.330000
16  2020-03-24   21.030000
17  2020-03-25   20.750000
18  2020-03-26   16.600000
19  2020-03-27   15.480000
20  2020-03-30   14.100000
21  2020-03-31   20.510000
22  2020-04-01   20.280000
23  2020-04-02   25.180000
24  2020-04-03   28.360000
25  2020-04-06   26.210000
26  2020-04-07   23.540000
27  2020-04-08   24.970000
28  2020-04-09   22.900000
29  2020-04-13   22.360000
30  2020-04-14   20.150000
31  2020-04-15   19.960000
32  2020-04-16   19.820000
33  2020-04-17   18.310000
34  2020-04-20  -36.980000
35  2020-04-21    8.910000
36  2020-04-22   13.640000
37  2020-04-23   15.060000
38  2020-04-24   15.990000
39  2020-04-27   12.170000
40  2020-04-28   12.400000
41  2020-04-29   15.040000
42  2020-04-30   19.230000

In [73]:
import pandas as pd

lowest_price = """SELECT date, price_usd AS 
                  lowest_oil_price_of_10years 
                  FROM oil_prices
                  WHERE date >= CURRENT_DATE - INTERVAL 10 YEAR
                  ORDER BY price_usd ASC
                  LIMIT 1;
                  """

cpa_cursor.execute(lowest_price)

lowest_price = cpa_cursor.fetchall()

lowest_oil_price_of_10years = pd.DataFrame(lowest_price,columns = [col[0] for col in cpa_cursor.description])

lowest_oil_price_of_10years

#lowest price of oil in the last 10 years. completed

         date lowest_oil_price_of_10years
0  2020-04-20                  -36.980000

In [74]:
import pandas as pd

votality_prices = """SELECT 
                           YEAR(date) AS year,
                           MAX(price_usd) AS Maxprice,
                           MIN(price_usd) AS Minprice,
                           (MAX(price_usd) - MIN(price_usd)) AS votality_of_oil_prices
                           FROM oil_prices
                           GROUP BY YEAR(date)
                           ORDER BY year;
                     """


cpa_cursor.execute(votality_prices)

votality_prices = cpa_cursor.fetchall()

votality_of_oil_prices = pd.DataFrame(votality_prices, columns =[col[0] for col in cpa_cursor.description])

votality_of_oil_prices


#Calculate the volatility of oil prices

   year    Maxprice    Minprice votality_of_oil_prices
0  2020   63.270000  -36.980000             100.250000
1  2021   85.640000   47.470000              38.170000
2  2022  123.640000   71.050000              52.590000
3  2023   93.670000   66.610000              27.060000
4  2024   87.690000   66.730000              20.960000
5  2025   80.730000   55.440000              25.290000
6  2026   64.770000   56.010000               8.760000

In [75]:
#oil_prices completed

In [76]:
import pandas as pd

all_stock_prices = """SELECT * FROM stock_prices
                      WHERE ticker IN  ("^GSPC","^IXIC","^NSEI")
                      ORDER BY ticker,date ASC"""

cpa_cursor.execute(all_stock_prices)

all_stock_prices = cpa_cursor.fetchall()

all_stock_prices = pd.DataFrame(all_stock_prices , columns =[col[0] for col in cpa_cursor.description])

all_stock_prices

#Get all stock prices for a given ticker completed

,date,open,high,low,close,volume,ticker
0,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3459930000,^GSPC
1,2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3484700000,^GSPC
2,2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3702460000,^GSPC
3,2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3435910000,^GSPC
4,2020-01-08,3238.590088,3267.070068,3236.669922,3253.050049,3726840000,^GSPC
...,...,...,...,...,...,...,...
3029,2026-01-23,25344.599609,25347.949219,25025.300781,25048.650391,393900,^NSEI
3030,2026-01-27,25063.349609,25246.650391,24932.550781,25175.400391,618700,^NSEI
3031,2026-01-28,25258.849609,25372.099609,25187.650391,25342.750000,574900,^NSEI
3032,2026-01-29,25345.000000,25458.150391,25159.800781,25418.900391,582400,^NSEI
3033,2026-01-30,25247.550781,25370.699219,25213.650391,25320.650391,508400,^NSEI

In [77]:
import pandas as pd 

highest_closing_price = """SELECT date,close FROM stock_prices
                           WHERE ticker = "^IXIC" ORDER BY 
                           close DESC LIMIT 1;"""

cpa_cursor.execute(highest_closing_price)

highest_closing_price = cpa_cursor.fetchall()

highest_closing_price_nasdaq = pd.DataFrame(highest_closing_price , columns = [col[0] for col in cpa_cursor.description])

highest_closing_price_nasdaq

#Find the highest closing price for NASDAQ (^IXIC) completed

Empty DataFrame
Columns: [date, close]
Index: []

In [78]:
import pandas as pd 

high_price_differance = """SELECT date,high,low,
                           (high - low) AS top_5_price_differance_gspc
                           FROM stock_prices
                           WHERE ticker = "^GSPC"
                           ORDER BY  top_5_price_differance_gspc
                           DESC LIMIT 5;"""

cpa_cursor.execute(high_price_differance) 

high_price_differance = cpa_cursor.fetchall()

top5_price_differance_gspc = pd.DataFrame(high_price_differance , columns =[col[0] for col in cpa_cursor.description])

top5_price_differance_gspc

#List top 5 days with highest price difference (high - low) for S&P 500 (^GSPC completed

         date         high          low top_5_price_differance_gspc
0  2025-04-09  5481.339844  4948.430176                  532.909668
1  2025-04-07  5246.569824  4835.040039                  411.529785
2  2025-04-08  5267.470215  4910.419922                  357.050293
3  2025-04-10  5353.149902  5115.270020                  237.879882
4  2025-11-20  6770.350098  6534.049805                  236.300293

In [79]:
import pandas as pd

monthly_average = """SELECT ticker,
                     DATE_FORMAT(date, "%Y-%m") AS month,
                     AVG(close) AS monthly_average_closing_price
                     FROM stock_prices
                     GROUP BY ticker, month
                     ORDER BY ticker, month
                     """

cpa_cursor.execute(monthly_average)

monthly_average = cpa_cursor.fetchall()

monthly_average_closing_price = pd.DataFrame(monthly_average, columns = [col[0] for col in cpa_cursor.description])

monthly_average_closing_price

#Get monthly average closing price for each ticker completed

    ticker    month monthly_average_closing_price
0    ^GSPC  2020-01               3278.2028576667
1    ^GSPC  2020-02               3277.3141832632
2    ^GSPC  2020-03               2652.3936323636
3    ^GSPC  2020-04               2761.9752255714
4    ^GSPC  2020-05               2919.6084838000
..     ...      ...                           ...
141  ^NSEI  2025-09              24942.6749821364
142  ^NSEI  2025-10              25494.0835192857
143  ^NSEI  2025-11              25894.8343955789
144  ^NSEI  2025-12              25997.7387250909
145  ^NSEI  2026-01              25652.9626953000

[146 rows x 3 columns]

In [80]:
import pandas as pd

average_trading = """SELECT ticker,
                     AVG(volume) AS average_trading_volume_2024
                     FROM stock_prices
                     WHERE ticker = "^NSEI"
                     AND YEAR(date) = 2024;
                     """

cpa_cursor.execute(average_trading)

average_trading = cpa_cursor.fetchall()

average_trading_volume_2024 = pd.DataFrame(average_trading, columns = [col[0] for col in cpa_cursor.description])

average_trading_volume_2024

#Get average trading volume of NSEI in 2024 completed

  ticker average_trading_volume_2024
0  ^NSEI                 313560.1626

In [81]:
#stocks_prices query completed

In [82]:
import pandas as pd

bitcoin_vs_oil = """SELECT 
                    bitcoin.avg_bitcoin_price_2025,
                    oil.avg_oil_price_2025
                    FROM
                    (SELECT AVG(price_usd) AS avg_bitcoin_price_2025
                    FROM crypto_prices
                    WHERE coin_id = "bitcoin"
                    AND YEAR(date) = 2025) AS bitcoin
                    
                    JOIN
                    
                    (SELECT AVG(price_usd) AS avg_oil_price_2025
                    FROM oil_prices
                    WHERE YEAR(date) = 2025)
                    AS oil
                    """

cpa_cursor.execute(bitcoin_vs_oil)

bitcoin_vs_oil = cpa_cursor.fetchall()

bitcoin_vs_oil_average_price_2025 = pd.DataFrame(bitcoin_vs_oil , columns = [col[0] for col in cpa_cursor.description])

bitcoin_vs_oil_average_price_2025 

#Compare Bitcoin vs Oil average price in 2025. completed

  avg_bitcoin_price_2025 avg_oil_price_2025
0      103199.7713814463      65.3881048387

In [83]:
import pandas as pd

btc_with_sap = """SELECT 
                  bitcoin.date,
                  bitcoin.price_usd AS bitcoin_price,
                  sp.close AS sp500_close
                  FROM crypto_prices bitcoin
                  JOIN stock_prices sp
                  ON bitcoin.date = sp.date
                  WHERE bitcoin.coin_id ="bitcoin"
                  AND sp.ticker = "^GSPC"
                  AND YEAR(bitcoin.date) = 2025
                  ORDER BY bitcoin.date;
                  """

cpa_cursor.execute(btc_with_sap)

btc_with_sap = cpa_cursor.fetchall()

bitcoin_moves_with_sandp500 = pd.DataFrame(btc_with_sap, columns = [col[0] for col in cpa_cursor.description])

bitcoin_moves_with_sandp500

#Check if Bitcoin moves with S&P 500 (correlation idea).completed

          date  bitcoin_price  sp500_close
0   2025-09-02  109229.014547  6415.540039
1   2025-09-03  111348.104293  6448.259766
2   2025-09-04  111751.647610  6502.080078
3   2025-09-05  110752.041425  6481.500000
4   2025-09-08  111133.092696  6495.149902
..         ...            ...          ...
80  2025-12-24   87496.146692  6932.049805
81  2025-12-26   87192.234737  6929.939941
82  2025-12-29   87867.039434  6905.740234
83  2025-12-30   87154.682406  6896.240234
84  2025-12-31   88363.722236  6845.500000

[85 rows x 3 columns]

In [89]:
import pandas as pd

ethereum_and_nasdaq = """SELECT ethereum.date,
                          ethereum.price_usd AS ethereum_price,
                          nasdaq.close AS nasdaq_close
                          FROM crypto_prices ethereum
                          JOIN stock_prices nasdaq
                          ON ethereum.date = nasdaq.date
                          WHERE ethereum.coin_id = 'ethereum'
                          AND nasdaq.ticker = '^IXIC'
                          AND YEAR(ethereum.date) = 2025
                          ORDER BY ethereum.date;
                          """

cpa_cursor.execute(ethereum_and_nasdaq)

ethereum_and_nasdaq = cpa_cursor.fetchall()

ethereum_and_nasdaq_dailyprices_2025 = pd.DataFrame(ethereum_and_nasdaq , columns = [col[0] for col in cpa_cursor.description])

ethereum_and_nasdaq_dailyprices_2025

#Compare Ethereum and NASDAQ daily prices for 2025. completed

Empty DataFrame
Columns: [date, ethereum_price, nasdaq_close]
Index: []

In [87]:
import pandas as pd

oil_spike_vs_bitcoinchange = """
                             SELECT *
                             FROM(
                             SELECT oil.date,
                             oil.price_usd AS oil_price,
                             oil.price_usd - LAG(oil.price_usd) OVER (ORDER BY oil.date) AS oil_spike,
                             bitcoin.price_usd AS bitcoin_price,
                             bitcoin.price_usd - LAG(bitcoin.price_usd) OVER (ORDER BY bitcoin.date) AS bitcoin_change
                             FROM oil_prices oil
                             JOIN crypto_prices bitcoin
                             ON oil.date = bitcoin.date
                             WHERE bitcoin.coin_id = 'bitcoin'
                             AND YEAR(oil.date) = 2025 
                             ) AS t
                             WHERE oil_spike > oil_price * 0.05 
                             ORDER BY date;
                             """

cpa_cursor.execute(oil_spike_vs_bitcoinchange)

oil_spike_vs_bitcoinchange = cpa_cursor.fetchall()

oil_price_spike_vs_bitcoin_price_change = pd.DataFrame(oil_spike_vs_bitcoinchange , columns = [col[0] for col in cpa_cursor.description])

oil_price_spike_vs_bitcoin_price_change

#Find days when oil price spiked and compare with Bitcoin price change. completed

         date  oil_price oil_spike  bitcoin_price bitcoin_change
0  2025-10-23  62.440000  3.140000  107591.460509    -710.294116

In [88]:
import pandas as pd

top3_coins = """SELECT 
                crypto.date,
                crypto.coin_id,
                crypto.price_usd AS coin_price,
                stock.close AS nifty_close
                FROM crypto_prices crypto
                JOIN stock_prices stock
                ON crypto.date = stock.date
                WHERE crypto.coin_id IN ('bitcoin','ethereum','tether')
                AND stock.ticker = "^NSEI"
                AND YEAR(crypto.date) = 2025
                ORDER BY crypto.date, crypto.coin_id;
             """

cpa_cursor.execute(top3_coins)

top3_coins = cpa_cursor.fetchall()

top3_coins_daily_price_trend_vs_Nifty = pd.DataFrame(top3_coins , columns = [col[0] for col in cpa_cursor.description])

top3_coins_daily_price_trend_vs_Nifty

#top 3 coins daily price trend vs Nifty completed

           date   coin_id     coin_price   nifty_close
0    2025-09-02   bitcoin  109229.014547  24579.599609
1    2025-09-02  ethereum    4314.336846  24579.599609
2    2025-09-02    tether       1.000070  24579.599609
3    2025-09-03   bitcoin  111348.104293  24715.050781
4    2025-09-03  ethereum    4320.560266  24715.050781
..          ...       ...            ...           ...
244  2025-12-30  ethereum    2934.356281  25938.849609
245  2025-12-30    tether       0.998910  25938.849609
246  2025-12-31   bitcoin   88363.722236  26129.599609
247  2025-12-31  ethereum    2967.980414  26129.599609
248  2025-12-31    tether       0.999032  26129.599609

[249 rows x 4 columns]

In [90]:
import pandas as pd

gspc_vs_oil = """
              SELECT
                  stock.date,
                  stock.close AS sp500_close,
                  oil.price_usd AS oil_price
              FROM stock_prices stock
              JOIN oil_prices oil
                 ON stock.date = oil.date
              WHERE stock.ticker = '^GSPC'
                AND YEAR(stock.date) = 2025
              ORDER BY stock.date;
              """
cpa_cursor.execute(gspc_vs_oil)

gspc_vs_oil = cpa_cursor.fetchall()

gspc_prices_vs_oil_prices_on_samedates = pd.DataFrame(gspc_vs_oil, columns = [col[0] for col in cpa_cursor.description])

gspc_prices_vs_oil_prices_on_samedates

#Compare stock prices (^GSPC) with crude oil prices on the same dates completed

           date  sp500_close  oil_price
0    2025-01-02  5868.549805  73.790000
1    2025-01-03  5942.470215  74.640000
2    2025-01-06  5975.379883  74.310000
3    2025-01-07  5909.029785  74.990000
4    2025-01-08  5918.250000  73.990000
..          ...          ...        ...
243  2025-12-24  6932.049805  58.720000
244  2025-12-26  6929.939941  56.600000
245  2025-12-29  6905.740234  57.890000
246  2025-12-30  6896.240234  57.790000
247  2025-12-31  6845.500000  57.260000

[248 rows x 3 columns]

In [91]:
import pandas as pd

bitcoin_vs_oil = """SELECT 
                    bitcoin.date,
                    bitcoin.price_usd AS bitcoin_price,
                    oil.price_usd AS oil_price
                    FROM crypto_prices bitcoin
                    JOIN oil_prices oil
                    ON bitcoin.date = oil.date
                    WHERE bitcoin.coin_id = 'bitcoin'
                    AND YEAR(bitcoin.date) = 2025
                    ORDER BY bitcoin.date;
                    """

cpa_cursor.execute(bitcoin_vs_oil)

bitcoin_vs_oil = cpa_cursor.fetchall()

bitcoin_closingprice_with_oilclosingprice_samedates = pd.DataFrame(bitcoin_vs_oil , columns = [col[0] for col in cpa_cursor.description])

bitcoin_closingprice_with_oilclosingprice_samedates

#Correlate Bitcoin closing price with crude oil closing price (same date) completed

          date  bitcoin_price  oil_price
0   2025-09-02  109229.014547  65.950000
1   2025-09-03  111348.104293  64.360000
2   2025-09-04  111751.647610  63.810000
3   2025-09-05  110752.041425  62.220000
4   2025-09-08  111133.092696  62.600000
..         ...            ...        ...
78  2025-12-24   87496.146692  58.720000
79  2025-12-26   87192.234737  56.600000
80  2025-12-29   87867.039434  57.890000
81  2025-12-30   87154.682406  57.790000
82  2025-12-31   88363.722236  57.260000

[83 rows x 3 columns]

In [92]:
import pandas as pd

nasdaq_vs_ethereum = """
                     SELECT ethereum.date,
                     ethereum.price_usd AS ethereum_price,
                     nasdaq.close AS nasdaq_close
                     FROM crypto_prices ethereum
                     JOIN stock_prices nasdaq
                     ON ethereum.date = nasdaq.date
                     WHERE ethereum.coin_id = 'ethereum'
                     AND nasdaq.ticker = '^IXIC'
                     AND YEAR(ethereum.date) = 2025
                     ORDER BY ethereum.date;
                     """

cpa_cursor.execute(nasdaq_vs_ethereum)

nasdaq_vs_ethereum = cpa_cursor.fetchall()

ixic_with_ethereum_pricetrends = pd.DataFrame(nasdaq_vs_ethereum , columns = [col[0] for col in cpa_cursor.description])

ixic_with_ethereum_pricetrends

#Compare NASDAQ (^IXIC) with Ethereum price trends completed successfully

Empty DataFrame
Columns: [date, ethereum_price, nasdaq_close]
Index: []

In [93]:
import pandas as pd

top3_crypto_with_stockindices = """
                                 SELECT 
                                 crypto.date,
                                 crypto.coin_id,
                                 crypto.price_usd AS coin_price,
                                 nsei.close AS nifty_close,
                                 gspc.close AS sp500_close,
                                 ixic.close AS nasdaq_close
                                 FROM crypto_prices crypto
                                 JOIN stock_prices nsei
                                 ON crypto.date = nsei.date AND nsei.ticker = '^NSEI'
                                 JOIN stock_prices gspc
                                 ON crypto.date = gspc.date AND gspc.ticker = '^GSPC'
                                 JOIN stock_prices ixic
                                 ON crypto.date = ixic.date AND ixic.ticker = '^IXIC'
                                 WHERE crypto.coin_id IN ('bitcoin','ethereum','tether')
                                 AND YEAR(crypto.date) = 2025
                                 ORDER BY crypto.date, crypto.coin_id;
                                 """
cpa_cursor.execute(top3_crypto_with_stockindices)

top3_crypto_with_stockindices = cpa_cursor.fetchall()

top3cryptocoins_with_stock_indices_2025 = pd.DataFrame(top3_crypto_with_stockindices, columns = [col[0] for col in cpa_cursor.description])

top3cryptocoins_with_stock_indices_2025

Empty DataFrame
Columns: [date, coin_id, coin_price, nifty_close, sp500_close, nasdaq_close]
Index: []

In [95]:
import pandas as pd

stock_oil_bitcoin = """
                    SELECT bitcoin.date,
                           bitcoin.price_usd AS bitcoin_price,
                           oil.price_usd AS oil_price,
                           nsei.close AS nifty_close,
                           gspc.close AS sp500_close,
                           ixic.close AS nasdaq_close
                    FROM crypto_prices bitcoin
                    JOIN oil_prices oil
                        ON bitcoin.date = oil.date
                    JOIN stock_prices nsei
                        ON bitcoin.date = nsei.date AND nsei.ticker = '^NSEI'
                    JOIN stock_prices gspc
                        ON bitcoin.date = gspc.date AND gspc.ticker = '^GSPC'
                    JOIN stock_prices ixic
                        ON bitcoin.date = ixic.date AND ixic.ticker = '^IXIC'
                    WHERE bitcoin.coin_id = 'bitcoin'
                      AND YEAR(bitcoin.date) = 2025
                    ORDER BY bitcoin.date;
                    """

cpa_cursor.execute(stock_oil_bitcoin)

stock_oil_bitcoin = cpa_cursor.fetchall()

stock_oil_bitcoin_daily_comparison = pd.DataFrame(stock_oil_bitcoin , columns = [col[0] for col in cpa_cursor.description])

stock_oil_bitcoin_daily_comparison

#Multi-join: stock prices, oil prices, and Bitcoin prices for daily comparison completed

Empty DataFrame
Columns: [date, bitcoin_price, oil_price, nifty_close, sp500_close, nasdaq_close]
Index: []

In [ ]:
# all_30_queries_finished

In [96]:
!pip install streamlit-option-menu

Defaulting to user installation because normal site-packages is not writeable
Collecting streamlit-option-menu
  Downloading streamlit_option_menu-0.4.0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: streamlit>=1.36 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit-option-menu) (1.58.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (6.0.0)
Requirement already satisfied: blinker<2,>=1.5.0 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (6.2.2)
Requirement already satisfied: click<9,>=7.0 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (8.4.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (3.1.50)
Requirement already satisfied: numpy<3,>=1.23 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (2.4.6)
Requirement already satisfied: packaging>=20 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (26.0)
Requirement already satisfied: pandas<4,>=1.4.0 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (3.0.3)
Requirement already satisfied: pillow<13,>=7.1.0 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (12.3.0)
Requirement already satisfied: protobuf<8,>=3.20 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (6.33.5)
Requirement already satisfied: pyarrow>=7.0 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (23.0.1)
Requirement already satisfied: requests<3,>=2.27 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (2.34.2)
Requirement already satisfied: tenacity<10,>=8.1.0 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (4.16.0)
Requirement already satisfied: starlette>=0.40.0 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (1.3.1)
Requirement already satisfied: uvicorn>=0.30.0 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (0.40.0)
Requirement already satisfied: httptools>=0.6.3 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (0.7.1)
Requirement already satisfied: anyio>=4.0.0 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (4.12.1)
Requirement already satisfied: python-multipart>=0.0.10 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (0.0.32)
Requirement already satisfied: websockets>=12.0.0 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (16.0)
Requirement already satisfied: itsdangerous>=2.1.2 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in C:\ProgramData\anaconda3\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (6.0.0)
Requirement already satisfied: jinja2 in C:\ProgramData\anaconda3\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in C:\ProgramData\anaconda3\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (4.25.1)
Requirement already satisfied: narwhals>=1.27.1 in C:\ProgramData\anaconda3\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (2.23.0)
Requirement already satisfied: colorama in C:\ProgramData\anaconda3\Lib\site-packages (from click<9,>=7.0->streamlit>=1.36->streamlit-option-menu) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in C:\ProgramData\anaconda3\Lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.36->streamlit-option-menu) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in C:\ProgramData\anaconda3\Lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.36->streamlit-option-menu) (4.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\ProgramData\anaconda3\Lib\site-packages (from pandas<4,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\ProgramData\anaconda3\Lib\site-packages (from pandas<4,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\ProgramData\anaconda3\Lib\site-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\ProgramData\anaconda3\Lib\site-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\ProgramData\anaconda3\Lib\site-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\ProgramData\anaconda3\Lib\site-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (2026.6.17)
Requirement already satisfied: attrs>=22.2.0 in C:\ProgramData\anaconda3\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\ProgramData\anaconda3\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in C:\ProgramData\anaconda3\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in C:\ProgramData\anaconda3\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (0.28.0)
Requirement already satisfied: six>=1.5 in C:\ProgramData\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (1.17.0)
Requirement already satisfied: h11>=0.8 in C:\ProgramData\anaconda3\Lib\site-packages (from uvicorn>=0.30.0->streamlit>=1.36->streamlit-option-menu) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\ProgramData\anaconda3\Lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (3.0.3)
Downloading streamlit_option_menu-0.4.0-py3-none-any.whl (829 kB)
   ---------------------------------------- 0.0/829.3 kB ? eta -:--:--
   ---------------------------------------- 0.0/829.3 kB ? eta -:--:--
   ------------ --------------------------- 262.1/829.3 kB ? eta -:--:--
   ------------------------- -------------- 524.3/829.3 kB 1.0 MB/s eta 0:00:01
   ---------------------------------------- 829.3/829.3 kB 1.1 MB/s  0:00:00
Installing collected packages: streamlit-option-menu
Successfully installed streamlit-option-menu-0.4.0